name: PassingCore
version: 1.0-SNAPSHOT
main: tw.sac.passingcore.PassingCorePlugin
api-version: '26.1.2'
commands:
  passgive:
    description: Give a PassingCore plugin item
    usage: /passgive [player] <item> [amount]
    permission: passingcore.passgive
permissions:
  passingcore.passgive:
    description: Allows giving PassingCore plugin items
    default: op
