name: PassingCore
version: 1.0-SNAPSHOT
main: tw.sac.passingcore.PassingCorePlugin
api-version: '26.1.2'
commands:
  passingitem:
    description: Give the decorative PassingCore custom item
    usage: /passingitem [amount]
    permission: passingcore.item
permissions:
  passingcore.item:
    description: Allows getting the decorative PassingCore custom item
    default: op
